<Project>
    <PropertyGroup>
        <Version>0.1.0.0</Version>
        <AssemblyVersion>0.1.0.0</AssemblyVersion>
        <FileVersion>0.1.0.0</FileVersion>
        <JellyfinPackageVersion>10.11.11</JellyfinPackageVersion>
        <JellyfinTargetAbi>10.11.11.0</JellyfinTargetAbi>
    </PropertyGroup>
</Project>
